development:
  adapter: postgresql
  encoding: utf-8
  min_messages: warning
  timeout: 5000
  username: <%= `whoami`.chomp %>
  database: studiovasco_development

test:
  adapter: postgresql
  encoding: utf-8
  min_messages: warning
  timeout: 5000
  username: <%= `whoami`.chomp %>
  database: studiovasco_test

production:
  adapter: postgresql
  encoding: utf-8
  min_messages: warning
  timeout: 5000
  username: <%= `whoami`.chomp %>
  database: studiovasco_production
